[package]
name = "keyhelper"
version = "0.1.0"
edition = "2021"
description = "unnecessary SSH-key manager mainly for my pleasure"
repository = "https://github.com/nrdrch/keyhelper"
license = "GPL-3.0+"
categories = ["command-line-utilities"]
[dependencies]
termcolor = "1.4.1"
